version: '3.9'

services:
  backend:
    build: ./Reddit
    container_name: reddit-backend
    env_file: ./Reddit/.env
    ports:
      - "5000:5000"
    volumes:
      - ./Reddit/uploads:/app/uploads
    depends_on:
      - mongo

  frontend:
    build: ./Front end
    container_name: reddit-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
